<?php

/**
 * @file
 * Module to restrict the number of nodes by role.
 */

/**
 * Implements hook_user_role_delete().
 *
 * Delete all rules related to the role being deleted.
 */
function node_limit_userofrole_user_role_delete($role) {
  $limits = db_select('node_limit_userofrole', 'src')
    ->fields('src', array('lid'))
    ->condition('role', $role->name)
    ->execute();
  $lids = array();
  foreach ($limits as $limit) {
    $lids[] = $limit->lid;
  }
  node_limit_delete($lids);
}

/**
 * Implements hook_node_limit_applies_in_context().
 */
function node_limit_userofrole_node_limit_applies_in_context($lid, $node, $user) {
  // By default, this Node Limit does NOT apply, but is actively enabled.
  $applies = NODE_LIMIT_LIMIT_DOESNT_APPLY;

  // Load the Node Limit object
  $limit = node_limit_userofrole_node_limit_load($lid);
  dpm($limit);

  // If there isn't a Node Limit, this submodule isn't even used right now.
  if (empty($limit)) {
    $applies = NODE_LIMIT_LIMIT_NEUTRAL;
  }
  elseif (!empty($user)) {
    // Is this limit placed on anonymous users?
    $isRoleAnonymous = $limit['node_limit_userofrole']['name'] == BACKDROP_ANONYMOUS_ROLE;
    // How about Authenticated Users? Is this Node Limit for them?
    $isRoleAuth = $limit['node_limit_userofrole']['name'] == BACKDROP_AUTHENTICATED_ROLE;

    if ((in_array($limit['node_limit_role']['name'], $user->roles)) || ($user->uid > 0 && $isRoleAnonymous) || ($user->uid == 0 && $isRoleAuth)) {
      $applies = NODE_LIMIT_LIMIT_DOES_APPLY;
    }
  }
  return array('node_limit_userofrole' => $applies);
}

/**
 * Implements hook_node_limit_sql().
 */
function node_limit_userofrole_node_limit_sql($lid, SelectQuery $select) {
  global $user;

  $limit = node_limit_userofrole_node_limit_load($lid);
  if (empty($limit)) {
    return;
  }

  $select->condition('uid', $user->uid);
}

/**
 * Implements hook_node_limit_element().
 */
function node_limit_userofrole_node_limit_element($lid = 0) {
  $limit = node_limit_userofrole_node_limit_load($lid);
  $role = !empty($limit['node_limit_userofrole']) ? $limit['node_limit_userofrole'] : array();
  $roles = user_roles();
  dpm($roles);

  if (!empty($roles)) {
    return array(
      'node_limit_userofrole' => array(
        '#type' => 'select',
        '#title' => t('Users of Role'),
        '#options' => $roles,
        '#default_value' => $role['name'],
      )
    );
  }
  return array();
}

/**
 * Implements hook_node_limit_element_validate().
 */
function node_limit_userofrole_node_limit_element_validate($element) {
  /**
   * Validation:
   * Check to see if the Role exists.
   */
  $roles = user_roles();
  if (!isset($roles[$element])) {
    // Unknown role.
    return array(
      'error' => t('Unknown role "%role"', array('%role' => $element))
    );
  }
  return TRUE;
}

/**
 * Implements hook_node_limit_save().
 */
function node_limit_userofrole_node_limit_save($lid, $applies, $element) {
  if ($applies) {
    // In the clone context, $element is an array containing the machine name and the role label.
    if (is_array($element)) {
      $element = $element['machine_name'];
    }

    try {
      db_insert('node_limit_userofrole')
        ->fields(array(
          'lid' => $lid,
          'role' => $element,
        ))
        ->execute();
    }
    catch (FieldsOverlapException $e) {
      backdrop_set_message(t('The Node Limit failed to save.'));
      watchdog_exception('node_limit_userofrole', $e);
    }
    catch (NoFieldsException $e) {
      watchdog_exception('node_limit_userofrole', $e);
    }
  }
}

/**
 * Implements hook_node_limit_delete().
 */
function node_limit_userofrole_node_limit_delete($lids) {
  db_delete('node_limit_userofrole')
    ->condition('lid', $lids, 'IN')
    ->execute();
}

/**
 * Implements hook_node_limit_load().
 */
function node_limit_userofrole_node_limit_load($lid) {
  // We want the Roles that have a Node Limit.
  $result = db_query('SELECT role FROM node_limit_userofrole WHERE lid = :lid', array(':lid' => $lid))->fetchField();
  $info = user_role_load($result);

  if (!empty($info->name)) {
    return array(
      'node_limit_userofrole' => array(
        'name' => $info->name, // The machine name
        'label' => $info->label // The Role label (e.g. 'My role label')
      )
    );
  }
  return array();
}
